import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StickyThemeSwitcher from "@/app/components/StickyThemeSwitcher";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import ClientProviders from "@/app/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
                      children,
                    }: Readonly<{ children: React.ReactNode }>) => {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
      <ClientProviders>
        <Header />
        <main className="mt-5 flex-grow">{children}</main>
        <Footer />
        <StickyThemeSwitcher />
      </ClientProviders>
      </body>
      </html>
  );
};

export default RootLayout;
