import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/context/ThemeContext";
import StickyThemeSwitcher from "@/app/components/StickyThemeSwitcher";
import Header from "@/app/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider> {/* ✅ Ensure ThemeProvider wraps all routes */}
          <Header />
          <main className="mt-5">
            {children}
          </main>
          <StickyThemeSwitcher /> {/* ✅ Ensure StickyThemeSwitcher is inside ThemeProvider */}
        </ThemeProvider>
      </body>
    </html>
  );
}
